### ISSUE TITLE
error while running LRscore

### ISSUE THREAD

**Issue by rahulnutron** [Jasonxu0109/PlantPhoneDB#1]
Dear PlantPhoneDB team,

Thanks for developing this tool! I am trying to apply this in my dataset which has about 80k cells. Then it failed with error. 
I tried to reduce the size by subsetting out only one dataset, however it again giving me error. I will be grateful if you could help me overcome this issue.

Rahul

1st error with big integrated data

> score_data <- LRscore(ra.integrated@assays$SCT@data, LRdb=LR_pair, cluster = Idents(ra.integrated), min.pct = 0.1,iterations=100, method='Average')
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

2nd error with only 808 cells

> dim(ra.integrated_jb)
[1] 26987   808

> score_data <- LRscore(ra.integrated_jb@assays$SCT@data, LRdb=LR_pair, cluster = Idents(ra.integrated_jb), min.pct = 0.1,iterations=100, method='Average')
Error in apply(tmp, 1, function(x) { : dim(X) must have a positive length

**Comment by Jasonxu0109** [comment]
Hi Rahul,

We are happy that you find our PlantPhoneDB useful. 
The first issue is that your data are required for necessary the memory on your laptop. You can run your data on the linux server. We guessed this problem is due to the matrix being too big making the as.data.frame function being failed. 

The second issue is that there are not enough cells for each cluster. You can delete some clusters without enough cells, or we advise you to change a downsampling method for your data in a stratified way.

Thanks for using this tool.

Best wishes,
Jasonxu

**Comment by rahulnutron** [comment]
Thanks you Jasonxu for quick reply! 
Yes the1st error is due to memory limit, I will try in server. 
You were right for the 2nd error, many clusters had less cells as I subset the data from integrated, I should have re-clustered again. When I make sure the number of cells in a cluster is sufficient, I received another error.

> score_data <- LRscore(ra.integrated_jb@assays$SCT@data, LRdb=LR_pair, cluster = Idents(ra.integrated_jb), iterations=100, method='average')
Error in score(l = tmp.L[tmp.LR$Ligands], r = tmp.R[tmp.LR$Receptors],  : 
  object 's' not found

Looks like its from processing of LR database, I used as suggested in the tutorial 

load(file="D:/LR_pair_ath.RDa")
LR_pair <- LR_pair %>%
  filter(source!="orthologs") %>%
  select(Ligands, Receptors) %>%
  unique()

**Comment by rahulnutron** [comment]
Hi, I found the reason of the above error: I have to use the method available in LRscore. I changed it to "LRScore" and it worked.

**Comment by Jasonxu0109** [comment]
Wow, good news!
